# Data {#sec:data}

```{r eval = FALSE, echo = FALSE}
pass_rush <- read_csv(here("data", "pass_rush.csv.gz"))
pass_rush %>% select(gameId, playId, frameId) %>% n_distinct()
```

In the forthcoming analysis, we rely on the data from the NFL Big Data Bowl 2023 provided by the NFL Next Gen Stats tracking system.
The data corresponds to 8,557 passing plays across 122 games in the first eight weeks of the 2021 NFL regular season. 
For each play, we have information on the on-field location, speed, angle, direction, and orientation of each player on the field and the football at a rate of 10 Hz (i.e., 10 measurements per second), along with event annotations for each frame such as ball snap, pass forward, and quarterback sack, to name a few.

For our investigation, we consider only the frames between the ball snap and when a pass forward or quarterback sack is recorded for each play.
We also remove all plays with multiple quarterbacks on the field, since we need a uniquely defined quarterback to compute our metric.
After preprocessing, there are 251,060 unique frames corresponding to moments of time from the start of the play at snap until the moment the quarterback either throws the pass or is sacked.

Throughout this paper, we use a [play](https://www.raiders.com/video/de-maxx-crosby-sacks-qb-teddy-bridgewater-for-a-loss-of-6-yards-nfl) from the 2021 NFL regular season week six matchup between the Las Vegas Raiders and Denver Broncos as a case study for examining pass rush in football.
Table C.1 of the Supplement displays a tracking data example for the aforementioned play, which ends with Broncos quarterback Teddy Bridgewater getting sacked by Raiders defensive end Maxx Crosby.

<!-- In addition, Figure \ref{fig:fig_field_raw} presents the locations of every Las Vegas (in black) and Denver (in orange) player on the field from this play at 1, 2, 3 and 4 seconds after the ball snap, with Maxx Crosby highlighted in blue.  -->

<!-- [^crosbysack]: Game footage of this play is available at https://www.raiders.com/video/de-maxx-crosby-sacks-qb-teddy-bridgewater-for-a-loss-of-6-yards-nfl -->

<!-- ```{r} -->
<!-- #| label: fig_field_raw -->
<!-- #| fig.cap: "A display of the player tracking data for a play during the Las Vegas Raiders (defense, in black) versus Denver Broncos (offense, in orange) NFL game on October 17, 2021. Raiders defensive end Maxx Crosby is highlighted in blue. Snapshots are captured at 1, 2, 3, and 4 seconds after the ball snap." -->
<!-- #| fig.width: 6.6 -->
<!-- #| fig.height: 4.4 -->
<!-- source(here("scripts", "11_fig_field_raw.R")) -->
<!-- fig_field_raw -->
<!-- ``` -->

Along with the tracking information, the Big Data Bowl 2023 includes scouting data provided by Pro Football Focus (PFF). 
This contains manually-collected player-level information, such as the player's role (e.g., whether they are a pass rusher and pass blocker) and credited events (e.g., player is credited with hitting the QB on the play).
In this manuscript, we use the PFF data to identify 36,362 unique pass rush attempts by players designated in the "pass rush" role across all plays.
For context, Figure D.1 of the Supplement displays the distribution of the number of observed pass rushers involved in a play, ranging from 1 to 8 with 4 pass rushers (i.e., 4-man rush formation) as the most common value.
We also leverage this scouting data to count how many hits, hurries, and sacks each pass rusher is credited with across the span of observed data. 
Additionally, we use the PFF player roles to identify the blocking matchup for each pass rusher in order to adjust for opponent strength, as discussed in Section \ref{sec:methods}.

<!-- For context, Figure \ref{fig:pass_rushers_count} displays the distribution of the number of observed pass rushers involved in a play, ranging from 1 to 8 with 4 pass rushers (i.e., 4-man rush formation) as the most common value. -->


<!-- ```{r} -->
<!-- #| label: pass_rushers_count -->
<!-- #| fig.cap: "Distribution of the number of pass rushers on passing plays." -->
<!-- #| fig.width: 3 -->
<!-- #| fig.height: 2.5 -->
<!-- source(here("scripts", "12_fig_pass_rushers_count.R")) -->
<!-- pass_rushers_count -->
<!-- ``` -->

