---
title: |
  | Here Comes the STRAIN: Analyzing Defensive Pass Rush in American Football with Player Tracking Data
  
# Deforming the line:
# Straining the line:
# Unleashing the Rush
# straining for the takedown
# straining for success
# straining forward
# straining for pressure
# Unleashing the Strain
# Strain on the Gridiron
# from strain to gain
# Bearing the Strain:
# Straining the trenches:
# Bearing the STRAIN

# to produce blinded version set to 1
blinded: 0

authors: 
- name: Quang Nguyen
  # thanks: Corresponding author's email
  affiliation: |
    | Department of Statistics & Data Science
    | Carnegie Mellon University
- name: Ronald Yurko
  affiliation: |
    | Department of Statistics & Data Science
    | Carnegie Mellon University
- name: Gregory J. Matthews
  affiliation: |
    | Department of Mathematics and Statistics
    | Center for Data Science and Consulting
    | Loyola University Chicago
    
keywords:
- American football
- defensive linemen
- multilevel model
- player tracking data

abstract: |
  In American football, a pass rush is an attempt by the defensive team to disrupt the offense and prevent the quarterback (QB) from completing a pass. Existing metrics for assessing pass rush performance are either discrete-time quantities or based on subjective judgment. Using player tracking data, we propose STRAIN, a novel metric for evaluating pass rushers in the National Football League (NFL) at the continuous-time within-play level. Inspired by the concept of strain rate in materials science, STRAIN is a simple and interpretable means for measuring defensive pressure in football. It is a directly-observed statistic as a function of two features: the distance between the pass rusher and QB, and the rate at which this distance is being reduced. Our metric possesses great predictability of pressure and stability over time. We also fit a multilevel model for STRAIN to understand the defensive pressure contribution of every pass rusher at the play-level. We apply our approach to NFL data and present results for the first eight weeks of the 2021 regular season. In particular, we provide comparisons of STRAIN for different defensive positions and play outcomes, and rankings of the NFL's best pass rushers according to our metric.

bibliography: bibliography.bib
biblio-style: chicago
output: rticles::asa_article
---

```{r}
#| label: setup
#| include: false
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.align = "center"
  # fig.pos = "p",
  # cache = TRUE
)
library(here)
library(tidyverse)
```

\newpage
\spacingset{1.45}

```{r child = "01-introduction.Rmd"}
```

```{r child = "02-data.Rmd"}
```

```{r child = "03-methods.Rmd"}
```

```{r child = "04-results.Rmd"}
```

```{r child = "05-discussion.Rmd"}
```

# Acknowledgements {-}

We thank the organizers of the NFL Big Data Bowl 2023 for hosting the competition and providing access to the data.

\bigskip
\begin{center}
{\large\bf SUPPLEMENTARY MATERIAL}
\end{center}

All code related to this paper is available at https://github.com/getstrained/intro-strain. The data provided by the NFL Big Data Bowl 2023 is available at https://www.kaggle.com/competitions/nfl-big-data-bowl-2023/data.

# References