---
title: |
  Introducing STRAIN: A simple and interpretable pass rush metric inspired by materials science
short_title: STRAIN
authors: 
- name: "Author 1"
  affiliation: "Address"
  city: "City"
  country: "Country"
  email: "email1\\@example.com"
- name: "Author 2"
  affiliation: "Address2"
  city: "City2"
  country: "Country2"
  email: "email2\\@example.com"
abstract: |
  Abstract goes here
keywords: tracking data, Bornn legacy, too much Canadian
bibliography: "bibliography"
output: rticles::rss_article
header-includes:
  \usepackage{setspace}
  \usepackage{booktabs}
---

\newpage

# Introduction

<!--
TODO: update citations after they're published
-->

In recent years, tracking data have replaced traditional box-score statistics and play-by-play data as the state-of-the-art tool for analyzing and deeper understanding different sports.

examples of past nfl tracking data projects

See @Baumer2023Big, @Macdonald2020Recreating, and @Kovalchik2023Player for more complete reviews on how tracking data have transformed sports analytics.

NFL, next gen stats https://operations.nfl.com/gameday/technology/nfl-next-gen-stats/

Importance of D-linemen, pass rush (Maybe talk about role of each position, edge vs interior, defensive formation)

Previous metrics: Greg's lit review, their flaws

## Previous Pass Rush Metrics

\begin{table}
\caption{A summary of previously-existed pass rush metrics. \label{tab:metrics}}
\centering
\begin{tabular}{ll}
\toprule
\textbf{Metric} & \textbf{Description}\\
\midrule
Sacks & a\\
Hits & a\\
Hurries & a\\
QB Pressures & a\\
Pass-Rush Productivity (PRP) & a\\
Time In Pocket (TIP) & a\\
Pass Rush Win Rate (PRWR) & Rate at which pass rusher beats pass block within 2.5 seconds after snap\\
\bottomrule
\end{tabular}
\end{table}

Table \ref{tab:metrics}

Sacks, hits, hurries, pressures

Officially tracked by the NFL since 1982, the most well known statistic for evaluating defensive linemen on pass rushing plays is the sack, which occurs when a defensive player tackles the quarterback behind the line of scrimmage before the quarterback is able to throw a pass.


https://www.pro-football-reference.com/about/advanced_stats.htm

Pressures: QB pressures (hurries + knockdowns + sack plays). Note that "sack plays" in this instance include both sacks and assists.

Hurried: Times QBs were hurried - defined as a situation when the QB is forced to throw the ball earlier than intended or is chased around/out of the pocket as the result of defensive pressure

Hit: Times QBs were hit - occurs when the QB hits the ground after a throw, not marked on a sack play

PFF's Pass-Rush Productivity (PRP)

https://www.pff.com/news/pro-signature-stats-spotlight-defensive-line

More recently metrics such as Time In Pocket (TIP) and Pass Rush Win Rate (PRWR) have also been proposed and are substantial improvements over the less sophisticated counting statistics. 

Pocket Time: Number of seconds the quarterback was in the pocket between the snap of the ball and a pass or the collapse of the pocket

@Burke2018Created

https://www.espn.com/nfl/story/_/id/24892208

2.5 seconds, arbitrary

While PRWR is certainly a step in the right direction, it takes continuous data and converts it to a binary win/loss, which is generally not recommended in statistical analysis


## Contributions of STRAIN


The remainder of this paper is outlined as follows.

# Methods

## Data

2023 bdb [@Howard2023NFL]

first 8 weeks 2021 season

tracking: locations of players and ball, 10 fps, 

pre-processing standardize

PFF scouting: pass rush role

sample restriction: remove plays w multiple QB

frames between snap and QB outcome (pass forward, sack)

sample size

## Strain rate in materials science


## Application to pass-rushing in football


# Results

## Example play

## Positional STRAIN curves


## Ranking the best pass-rushers


## Corr with pressure rate = (hits + sacks + hurries) per snap


## Statistical Properties of STRAIN

From @Franks2016Meta (github https://github.com/afranks86/meta-analytics)

Discrimination: Does the metric reliably differentiate between players?

Stability: Does the metric measure a quantity which is stable over time?

Independence: Does the metric provide new information?


# Discussion

# References
