---
title: "Response to Reviewers"
output: pdf_document
fontsize: 11pt
---

We thank the editor, associate editor, and two reviewers for their critical assessment of our paper.
Below, we provide a point-by-point response to their comments. 

# Reviewer 1

**Model assumptions**

> I really liked the multi-level model for STRAIN. That said, the model encodes some strong exchangeability assumptions that, in my opinion, are worth probing. Insofar as (i) pass blockers are nested within teams and (ii) different teams deploy different pass protection schemes/techniques, have you considered an elaborated model in which pass blocker effects are first shrunk towards a team-specific average, which themselves are shrunk to a league-wide average? Perhaps more importantly, as you noted in Section 4.3, the model ignores correlated performance between defensive linemen on the same team. To account for this, you could, similarly nest pass rushers within teams. Doing so, however, introduces positive dependence between the $R_j$'s and it is not obvious to me that two teammates' strains on the same play should be positively correlated. We might observe negative dependence, for instance, if pass blockers concentrated more on blocking one player over another. At the very least, you should discuss the assumptions underpinning the multi-level model. A clear demonstrate that the proposed model provides a better fit to the data than alternatives would, of course, be much better!

> Relatedly, is there a reason to model the average STRAIN across a play as opposed to the frame-level STRAIN values? The two example plays reveal considerable variation in the frame-to-frame variability. I worry that simply averaging over all frames in a play might obscure this variation.

**Strain curves**

> I was a bit confused by the STRAIN curves in Figure 7. Are these curves based on a single play? Are they averages of the observed $\overline{\text{STRAIN}}_{ij}$'s values across all plays and all players within positions? Or are they averages of the estimated $\overline{\text{STRAIN}}$ values from the fitted multi-level model? If these curves are based solely on the observed $\overline{\text{STRAIN}}$ values, to what extent can the positional differences be explained by the fact that different pass rush positions tend to be blocked by different offensive line positions? Since multi-level model allows you to adjusting for the position of the nearest pass blocker, it would be interesting to see whether the differences observed between the curves persist after such adjustment.

**Minor comments**

> The $f_{d_{ij}}(t)$ notation in Equations (3)–(5) seems cumbersome. What is $f$ and why is indexed by a distance? Why not just use $d_{ij}(t)$ for the distance?

> Fixed effects in the multi-level model: it would be helpful to describe what variables are recorded in $\mathbf{x}$ when you introduce the multi-level model instead of in a table towards the end.


# Reviewer 2

> Page 3: It seems the author is defining anyone who lines up on the line of scrimmage outside a DE. This is not always agreed upon, I would recommend the authors make how they're defining that clear. Is it per play? Or is one player defined as always being a DE?

> Page 13: other fixed effects – this part feels a little rushed. I'd like to see more on why you chose those fixed effects.

> Page 13: mixed effects model – the way this is written, if a quarterback tends to have more pass rushers or less pass rushers than an average QB, there may be some effect on his random effect of average STRAIN that is due to the this effect

> I know time to throw is a fixed effect here, but are we worried that the causal relationship might be that average STRAIN acts on time to throw and not the other way around?

> Why is this random effects model focused on 1 rusher x 1 blocker x 1 qb at a time and not try to put all the players who are present on the field at the same time in the same model? This current format will likely have a lot of teammate effects bleeding into the estimate of another teammate due to being on the field so often together. ( you mention this briefly on page 24 and again in the conclusion – could add to the literature of APM metrics in football (Sabin, 2021).

# Associate Editor

1. The first comment that warrants serious consideration is whether the average strain, across an entire play, is the best way to summarize a pash rushers effect on a particular play. Furthermore, and as just one example, would this summary consistently capture the pash rusher effect across plays of different length?

2. Summarizing the pass rush / pass blocker scheme to a one rusher vs. one defender was also highlighted as a place of concern by both referees. Team pass blocking schemes, multiple pass blockers, and/or changing blockers over the course of the play could all be influential here.

# Editor

1. Avoid abbreviations except obvious ones like NFL and QB. Your paper is short enough (without tables/figures) that we can afford not to use them. This also relates to readability for our readers who are not football experts. See remark #6 below.

2. Reduce the number of tables and figures--you currently have 19 combined. My usual limit is 6-7, but I realize this submission may need to use more in the manuscript. A supplementary article can be used to house additional figures and additional work required to complete this revision. Please see recent issues of TAS for guidance on constructing the supplement. Please submit your revised article and supplement as separate .pdf files.

3. Do not use footnotes on pages 7 and 16. Either absorb into the text (somewhere) if critical or remove them.

4. You might consider using different plotting symbols in Figure 2, for example, when referring to the blue and orange dots. I'm thinking ahead if you want to avoid having to pay for extra charges which relate to the use of color. Same with Figure 4 and others. I'll leave this to you.

5. Only number those equations which are referred to later in the exposition.

6. Overall comment: Not all of our readers will be football experts like in sports analytics journal submissions. Please try to revise with this in mind. Use language that will make your paper inviting for all readers. Have any NFL teams used your methods? You might mention this in the Discussion section if appropriate.